import {useEffect,useRef,useState} from 'react';
import {io,Socket} from 'socket.io-client';
import './style.css';
const API=import.meta.env.VITE_API||'';
const socket:Socket=io(API,{autoConnect:false});
const skins:any={default:['Default',0,'🔢'],neon:['Neon',2500,'🟣'],fire:['Fire',5000,'🔥'],ice:['Ice',7500,'❄️'],electric:['Electric',10000,'⚡'],rainbow:['Rainbow',25000,'🌈'],diamond:['Diamond',50000,'💎'],galaxy:['Galaxy',100000,'🌌']};
type User={username:string;coins:number;wins:number;games:number;losses:number;level:number;xp:number;inventory:string[];equipped:string;seasonXp?:number;claimedSeason?:number[]};
type Bot={secret:number;min:number;max:number;turn:string;guesses:any[];state:string};type Room={id:string;code?:string;name?:string;entry:number;range:number;maxPlayers:number;players:any[];state:string;min:number;max:number;turn:number;guesses:any[];winner?:string};
export default function App(){
 const[user,setUser]=useState<User|null>(null),[mode,setMode]=useState('login'),[name,setName]=useState(''),[pw,setPw]=useState(''),[screen,setScreen]=useState('menu'),[rooms,setRooms]=useState<Room[]>([]),[room,setRoom]=useState<Room|null>(null),[code,setCode]=useState(''),[msg,setMsg]=useState(''),[guess,setGuess]=useState(''),[admin,setAdmin]=useState(''),[lang,setLang]=useState('es'),[drag,setDrag]=useState(false),[rank,setRank]=useState<any>(null),[bot,setBot]=useState<Bot>({secret:0,min:1,max:100,turn:'player',guesses:[],state:'waiting'}),[cam,setCam]=useState(0);const sx=useRef(0);
 useEffect(()=>{const s=localStorage.getItem('guessit-user');if(s)setUser(JSON.parse(s));socket.on('room:update',(r)=>{setRoom(r);if(r.state==='playing'||r.state==='waiting')setScreen('room')});socket.on('error:msg',setMsg);return()=>{socket.off('room:update');socket.off('error:msg')}},[]);
 const api=async(path:string,body:any)=>{const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error);return j};
 const auth=async()=>{try{const j=await api(mode==='login'?'/api/login':'/api/register',{username:name,password:pw});setUser(j.user);localStorage.setItem('guessit-user',JSON.stringify(j.user));setScreen('menu');setMsg('')}catch(e:any){setMsg(e.message)}};
 const load=async()=>{setRooms(await(await fetch(API+'/api/rooms')).json());setScreen('play')};
 const join=(r:Room)=>{setRoom(r);socket.connect();socket.emit('room:join',{roomId:r.id,username:user!.username});setScreen('room')};
 const create=async()=>{try{const j=await api('/api/rooms/create',{username:user!.username,entry:500,range:100});setRoom(j.room);socket.connect();socket.emit('room:join',{roomId:j.room.id,username:user!.username});setMsg('Room created!')}catch(e:any){setMsg(e.message)}};
 const redeem=async()=>{try{const j=await api('/api/redeem',{username:user!.username,code:admin});setUser(j.user);localStorage.setItem('guessit-user',JSON.stringify(j.user));setMsg(j.message);setAdmin('')}catch(e:any){setMsg(e.message)}};
 const buy=async(item:string)=>{try{const j=await api('/api/shop/buy',{username:user!.username,item});setUser(j.user);localStorage.setItem('guessit-user',JSON.stringify(j.user))}catch(e:any){setMsg(e.message)}};
 const equip=async(item:string)=>{try{const j=await api('/api/shop/equip',{username:user!.username,item});setUser(j.user);localStorage.setItem('guessit-user',JSON.stringify(j.user))}catch(e:any){setMsg(e.message)}};
 useEffect(()=>{if(screen!=='bot'||bot.state!=='playing'||bot.turn!=='bot')return;const timer=setTimeout(()=>{const n=Math.floor((bot.min+bot.max)/2);let min=bot.min,max=bot.max,result='correct';if(n<bot.secret){min=n+1;result='higher'}else if(n>bot.secret){max=n-1;result='lower'}const guesses=[...bot.guesses,{player:'BOT',number:n,result}];if(result==='correct'){api('/api/bot/result',{username:user?.username,won:false}).then(j=>{if(j.user){setUser(j.user);localStorage.setItem('guessit-user',JSON.stringify(j.user))}});setMsg('🤖 El bot ha ganado.');setBot({...bot,state:'finished',guesses,turn:'player'})}else setBot({...bot,min,max,turn:'player',guesses})},700);return()=>clearTimeout(timer)},[screen,bot.turn,bot.state,bot.min,bot.max,bot.guesses,user?.username]);
if(!user)return <div className="auth"><div className="card"><h1>GUESS<span>IT</span></h1><h2>{mode==='login'?'Iniciar sesión':'Crear cuenta'}</h2><input placeholder="Usuario" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Contraseña" type="password" value={pw} onChange={e=>setPw(e.target.value)}/><button onClick={auth}>{mode==='login'?'ENTRAR':'CREAR CUENTA'}</button><button className="ghost" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Crear cuenta':'Ya tengo cuenta'}</button>{msg&&<p className="msg">{msg}</p>}</div></div>;
 if(screen==='play')return <><Header user={user}/><main><h1>ELIGE UNA <span>SALA</span></h1><p>← Arrastra horizontalmente →</p><div className="rooms">{rooms.map(r=><button className="room" key={r.id} onClick={()=>join(r)}><b>{r.name}</b><div className="big">🪙 {r.entry.toLocaleString()}</div><small>👥 2-6 · 🔢 1-{r.range}</small><strong>JUGAR →</strong></button>)}</div><button onClick={()=>setScreen('menu')}>← VOLVER</button></main></>;
 if(screen==='friends')return <><Header user={user}/><main><h1>JUGAR CON <span>AMIGOS</span></h1><div className="card"><button onClick={create}>🚀 CREAR SALA</button><p>{msg}</p><input placeholder="Introduzca un código de sala" value={code} onChange={e=>setCode(e.target.value)}/><button onClick={async()=>{try{const j=await api('/api/rooms/join',{username:user.username,code});setRoom(j.room);socket.connect();socket.emit('room:join',{roomId:j.room.id,username:user.username});setScreen('room')}catch(e:any){setMsg(e.message)}}}>UNIRSE</button></div><button onClick={()=>setScreen('menu')}>← VOLVER</button></main></>;
 if(screen==='bot')return <><Header user={user}/><main><h1>JUGAR CONTRA <span>BOTS</span></h1><div className="card"><p>🤖 Bot Normal · 1-100</p><button onClick={()=>{const s=Math.floor(Math.random()*100)+1;setBot({secret:s,min:1,max:100,turn:'player',guesses:[],state:'playing'})}}>🚀 EMPEZAR PARTIDA</button></div>{bot.state==='playing'&&<><p>Turno: <b>{bot.turn==='player'?user.username:'BOT'}</b></p>{bot.turn==='player'&&<div className="numbers">{Array.from({length:100},(_,i)=>i+1).map(n=><button key={n} disabled={n<bot.min||n>bot.max} onClick={()=>{let min=bot.min,max=bot.max,result='correct';if(n<bot.secret){min=n+1;result='higher'}else if(n>bot.secret){max=n-1;result='lower'}const guesses=[...bot.guesses,{player:user.username,number:n,result}];if(result==='correct'){api('/api/bot/result',{username:user.username,won:true}).then(j=>{setUser(j.user);localStorage.setItem('guessit-user',JSON.stringify(j.user));setMsg('🎯 ¡Ganaste! +500 monedas')});setBot({...bot,state:'finished',guesses})}else setBot({...bot,min,max,turn:'bot',guesses})}}>{n}</button>)}</div>}{bot.turn==='bot'&&<p>🤖 El bot está pensando...</p>}{bot.guesses.map((g:any,i:number)=><div className="history" key={i}>{g.player} → {g.number} {g.result==='higher'?'⬆️ Más alto':g.result==='lower'?'⬇️ Más bajo':'🎯 CORRECTO'}</div>)}</>}{bot.state==='finished'&&<div className="card"><h2>🏁 Partida terminada</h2><button onClick={()=>setScreen('menu')}>CONTINUAR</button></div>}<button onClick={()=>setScreen('menu')}>← VOLVER</button></main></>;
 if(screen==='ranking')return <><Header user={user}/><main><h1><span>CLASIFICACIÓN</span></h1><div className="card"><h2>🪙 Más dinero</h2>{rank?.money?.map((u:any,i:number)=><p key={u.username}>#{i+1} <b>{u.username}</b> — 🪙 {u.coins.toLocaleString()}</p>)}</div><div className="card"><h2>🏆 Más victorias</h2>{rank?.wins?.map((u:any,i:number)=><p key={u.username}>#{i+1} <b>{u.username}</b> — {u.wins} victorias</p>)}</div><button onClick={()=>setScreen('menu')}>← VOLVER</button></main></>;
 if(screen==='profile')return <><Header user={user}/><main><h1><span>PERFIL</span></h1><div className="card"><div className="avatar">👤</div><h2>{user.username}</h2><p>🏆 Victorias: <b>{user.wins}</b></p><p>❌ Derrotas: <b>{user.losses}</b></p><p>🎮 Partidas jugadas: <b>{user.games}</b></p><p>🪙 Monedas: <b>{user.coins.toLocaleString()}</b></p><p>⭐ Nivel: <b>{user.level}</b> · XP: <b>{user.xp}</b></p></div><button onClick={()=>setScreen('menu')}>← VOLVER</button></main></>;
 if(screen==='season')return <><Header user={user}/><main><h1><span>TEMPORADA 1</span></h1><div className="card"><h2>⭐ {(user as any).seasonXp||0} XP</h2><p>Gana partidas para desbloquear recompensas.</p></div>{[{level:1,xp:0,coins:0},{level:2,xp:100,coins:1000},{level:3,xp:250,coins:2500},{level:4,xp:450,coins:5000},{level:5,xp:700,coins:10000},{level:6,xp:1000,coins:25000}].map(r=>{const xp=(user as any).seasonXp||0,claimed=((user as any).claimedSeason||[]).includes(r.level);return <div className="card" key={r.level}><h2>Nivel {r.level}</h2><p>⭐ {r.xp} XP · 🪙 {r.coins.toLocaleString()}</p><button disabled={xp<r.xp||claimed} onClick={()=>api('/api/season/claim',{username:user.username,level:r.level}).then(j=>{setUser(j.user);localStorage.setItem('guessit-user',JSON.stringify(j.user));setMsg(j.message)}).catch((e:any)=>setMsg(e.message))}>{claimed?'RECLAMADA':xp>=r.xp?'🎁 RECLAMAR':'🔒 BLOQUEADA'}</button></div>})}<button onClick={()=>setScreen('menu')}>← VOLVER</button></main></>;
 if(screen==='admin')return <><Header user={user}/><main><h1>ADMIN <span>PANEL</span></h1><div className="card"><input placeholder="Introduzca un codigo." value={admin} onChange={e=>setAdmin(e.target.value)}/><button onClick={redeem}>🎁 CANJEAR</button><p>{msg}</p></div><button onClick={()=>setScreen('menu')}>← VOLVER</button></main></>;
 if(screen==='shop')return <><Header user={user}/><main><h1><span>TIENDA</span></h1><div className="shop">{Object.entries(skins).map(([id,t])=><div className="item" key={id}><div className={'texture '+id}>{t[2]}</div><h2>{t[0]}</h2><p>{t[1]?'🪙 '+t[1].toLocaleString():'GRATIS'}</p>{user.inventory.includes(id)?<button onClick={()=>equip(id)}>{user.equipped===id?'EQUIPADO':'EQUIPAR'}</button>:<button onClick={()=>buy(id)}>COMPRAR</button>}</div>)}</div><button onClick={()=>setScreen('menu')}>← VOLVER</button></main></>;
 if(screen==='settings')return <><Header user={user}/><main><h1><span>AJUSTES</span></h1><div className="card"><label>🌐 Idioma</label><select value={lang} onChange={e=>setLang(e.target.value)}><option value="es">🇪🇸 Español</option><option value="en">🇬🇧 English</option></select></div><button onClick={()=>setScreen('menu')}>← VOLVER</button></main></>;
 if(screen==='room'&&room)return <><Header user={user}/><main><div className="room3d" onMouseDown={e=>{setDrag(true);sx.current=e.clientX}} onMouseUp={()=>setDrag(false)} onMouseLeave={()=>setDrag(false)} onMouseMove={e=>{if(drag){setCam(c=>c+(e.clientX-sx.current)*.25);sx.current=e.clientX}}} style={{transform:'perspective(900px) rotateY('+cam+'deg)'}}><div className="playersCircle">{room.players.map((p,i)=>{const n=Math.max(room.players.length,1);return <button className={'player '+(room.state==='playing'&&i===room.turn?'turn':'')} key={p.username} style={{transform:'rotate('+(i*360/n)+'deg) translateY(-190px) rotate('+(-i*360/n)+'deg)'}} onClick={()=>setMsg(p.username+': '+p.wins+' victorias · '+p.games+' partidas · '+p.losses+' derrotas')}><div className="avatar">👤</div><b>{p.username}</b>{room.state==='playing'&&i===room.turn&&<small>◉ TURNO</small>}</button>})}<div className="table"><b>{room.state==='waiting'?'ESPERANDO JUGADORES':room.state==='finished'?'🏆 '+room.winner:room.min+' - '+room.max}</b></div></div></div>{room.state==='waiting'&&room.players.length>=2&&<button onClick={()=>socket.emit('game:start',{roomId:room.id})}>🚀 EMPEZAR PARTIDA</button>}{room.state==='waiting'&&room.players.length<2&&<p>Esperando al menos 2 jugadores...</p>}{room.state==='playing'&&<><div className="numbers">{Array.from({length:room.range},(_,i)=>i+1).map(n=><button key={n} className={n<room.min||n>room.max?'disabled':''} disabled={n<room.min||n>room.max} onClick={()=>setGuess(String(n))}>{n}</button>)}</div><div className="guess"><input type="number" min={room.min} max={room.max} placeholder={room.min+' - '+room.max} value={guess} onChange={e=>setGuess(e.target.value)} onKeyDown={e=>e.key==='Enter'&&socket.emit('game:guess',{roomId:room.id,username:user.username,number:Number(guess)})}/><button onClick={()=>socket.emit('game:guess',{roomId:room.id,username:user.username,number:Number(guess)})}>ADIVINAR</button></div><p>Turno: <b>{room.players[room.turn]?.username}</b></p></>}{room.guesses.map((g,i)=><div className="history" key={i}>{g.player} → {g.number} {g.result==='higher'?'⬆️ Más alto':g.result==='lower'?'⬇️ Más bajo':'🎯 CORRECTO'}</div>)}{msg&&<p className="msg">{msg}</p>}<button onClick={()=>setScreen('menu')}>← SALIR</button></main></>;
 return <><Header user={user}/><main><p>BIENVENIDO, {user.username.toUpperCase()}</p><h1>¿PUEDES <span>ADIVINARLO?</span></h1><div className="menuBtns"><button onClick={load}>🎮 JUGAR<small>Elige una sala</small></button><button onClick={()=>setScreen('friends')}>👥 JUGAR CON AMIGOS<small>Crea una sala privada</small></button><button onClick={load}>🌐 JUGAR ONLINE<small>Encuentra jugadores</small></button><button onClick={()=>setScreen("bot")}>🤖 JUGAR CONTRA BOTS<small>Juega contra un bot</small></button></div><div className="bottom"><button onClick={()=>setScreen('shop')}>🛒 TIENDA</button><button onClick={()=>setScreen("profile")}>👤 PERFIL</button><button onClick={async()=>{const j=await(await fetch(API+"/api/rankings")).json();setRank(j);setScreen("ranking")}}>🏆 CLASIFICACIÓN</button><button onClick={()=>setScreen("season")}>⭐ TEMPORADA</button><button onClick={()=>setScreen('settings')}>⚙️ AJUSTES</button><button onClick={()=>setScreen('admin')}>🔐 ADMIN PANEL</button></div><p className="coins">🪙 {user.coins.toLocaleString()}</p></main></>}
function Header({user}:{user:User}){return <header><b>GUESS<span>IT</span></b><div>🪙 {user.coins.toLocaleString()} · 👤 {user.username}</div></header>}
