import express from'express';import cors from'cors';import http from'http';import{Server}from'socket.io';import bcrypt from'bcryptjs';import fs from'fs';import path from'path';import{fileURLToPath}from'url';
const dir=path.dirname(fileURLToPath(import.meta.url)),data=path.join(dir,'../data'),file=path.join(data,'db.json');if(!fs.existsSync(data))fs.mkdirSync(data,{recursive:true});if(!fs.existsSync(file))fs.writeFileSync(file,JSON.stringify({users:{},codes:{'10000Coins':{coins:10000,unlimited:false}}},null,2));const load=()=>JSON.parse(fs.readFileSync(file,'utf8')),save=x=>fs.writeFileSync(file,JSON.stringify(x,null,2));
const app=express();app.use(cors());app.use(express.json());const server=http.createServer(app),io=new Server(server,{cors:{origin:'*'}}),rooms=new Map();
const fees=[500,1000,2500,5000,10000,25000,50000,100000,250000],ranges=[100,100,250,250,500,500,1000,2500,5000],names=['Bronze Room','Silver Room','Gold Room','Diamond Room','Platinum Room','Ruby Room','Master Room','Elite Room','Legend Room'];const publics=fees.map((entry,i)=>({id:'public-'+i,name:names[i],entry,range:ranges[i]}));
const safe=u=>({username:u.username,coins:u.coins,wins:u.wins,games:u.games,losses:u.losses,level:u.level,xp:u.xp,inventory:u.inventory,equipped:u.equipped});
app.get('/api/health',(_,res)=>res.json({ok:true}));
app.post('/api/register',async(req,res)=>{const{username,password}=req.body;if(!username||!password||username.length<3||password.length<4)return res.status(400).json({error:'Usuario o contraseña no válidos.'});const db=load(),k=username.toLowerCase();if(db.users[k])return res.status(409).json({error:'El usuario ya existe.'});const u={username,password:await bcrypt.hash(password,10),coins:3000,wins:0,games:0,losses:0,level:1,xp:0,inventory:['default'],equipped:'default',usedCodes:[]};db.users[k]=u;save(db);res.json({user:safe(u)})});
app.post('/api/login',async(req,res)=>{const{username,password}=req.body,db=load(),u=db.users[(username||'').toLowerCase()];if(!u||!(await bcrypt.compare(password||'',u.password)))return res.status(401).json({error:'Usuario o contraseña incorrectos.'});res.json({user:safe(u)})});
app.post('/api/redeem',(req,res)=>{const{username,code}=req.body,db=load(),u=db.users[(username||'').toLowerCase()],c=db.codes[code];if(!u||!c)return res.status(400).json({error:'Código no válido.'});u.usedCodes=u.usedCodes||[];if(!c.unlimited&&u.usedCodes.includes(code))return res.status(400).json({error:'Ya has utilizado este código.'});u.coins+=c.coins;if(!c.unlimited)u.usedCodes.push(code);save(db);res.json({user:safe(u),message:'+'+c.coins.toLocaleString('es-ES')+' monedas.'})});
const items={neon:2500,fire:5000,ice:7500,electric:10000,rainbow:25000,diamond:50000,galaxy:100000};
app.post('/api/shop/buy',(req,res)=>{const{username,item}=req.body,db=load(),u=db.users[(username||'').toLowerCase()];if(!u||items[item]===undefined)return res.status(400).json({error:'Compra no válida.'});if(u.inventory.includes(item))return res.status(400).json({error:'Ya tienes este objeto.'});if(u.coins<items[item])return res.status(400).json({error:'No tienes suficientes monedas.'});u.coins-=items[item];u.inventory.push(item);save(db);res.json({user:safe(u)})});
app.post('/api/shop/equip',(req,res)=>{const{username,item}=req.body,db=load(),u=db.users[(username||'').toLowerCase()];if(!u||!u.inventory.includes(item))return res.status(400).json({error:'No tienes esta textura.'});u.equipped=item;save(db);res.json({user:safe(u)})});
app.get('/api/rooms',(_,res)=>res.json(publics.map(r=>({...r,players:rooms.get(r.id)?.players.length||0,maxPlayers:6}))));
function newRoom(host,entry=500,range=100){const id='custom-'+Math.random().toString(36).slice(2,8).toUpperCase(),code=Math.random().toString(36).slice(2,8).toUpperCase(),r={id,code,host,entry,range,maxPlayers:6,players:[],state:'waiting',secret:null,min:1,max:range,turn:0,guesses:[],winner:null};rooms.set(id,r);return r}
app.post('/api/rooms/create',(req,res)=>res.json({room:newRoom(req.body.username,req.body.entry||500,req.body.range||100)}));
app.post('/api/rooms/join',(req,res)=>{const r=[...rooms.values()].find(x=>x.code===String(req.body.code||'').toUpperCase());if(!r)return res.status(404).json({error:'Sala no encontrada.'});if(r.players.length>=6)return res.status(409).json({error:'Sala llena.'});res.json({room:r})});
const sync=r=>io.to(r.id).emit('room:update',{...r,secret:undefined,players:r.players.map(p=>({username:p.username,equipped:p.equipped,wins:p.wins,games:p.games,losses:p.losses}))});
function pub(id){let r=rooms.get(id);if(r)return r;const p=publics[Number(id.slice(7))];if(!p)return null;r={...p,code:null,host:null,maxPlayers:6,players:[],state:'waiting',secret:null,min:1,max:p.range,turn:0,guesses:[],winner:null};rooms.set(id,r);return r}
io.on('connection',s=>{s.on('room:join',({roomId,username})=>{const r=pub(roomId)||rooms.get(roomId);if(!r)return s.emit('error:msg','Sala no encontrada.');if(r.players.some(p=>p.username===username))return;if(r.players.length>=6)return s.emit('error:msg','Sala llena.');const u=load().users[username.toLowerCase()];r.players.push({username,equipped:u?.equipped||'default',wins:u?.wins||0,games:u?.games||0,losses:u?.losses||0,socketId:s.id});s.join(r.id);s.data.roomId=r.id;s.data.username=username;sync(r)});
s.on('game:start',({roomId})=>{const r=rooms.get(roomId);if(!r||r.players.length<2||r.state!=='waiting')return;r.state='playing';r.secret=Math.floor(Math.random()*r.range)+1;r.min=1;r.max=r.range;r.turn=0;r.guesses=[];r.winner=null;sync(r)});
s.on('game:guess',({roomId,username,number})=>{const r=rooms.get(roomId);if(!r||r.state!=='playing')return;const p=r.players[r.turn];if(!p||p.username!==username)return s.emit('error:msg','No es tu turno.');number=Number(number);if(!Number.isInteger(number)||number<r.min||number>r.max)return s.emit('error:msg','Número fuera de rango.');let result='correct';if(number<r.secret){r.min=number+1;result='higher'}else if(number>r.secret){r.max=number-1;result='lower'}r.guesses.unshift({player:username,number,result});if(result==='correct'){r.state='finished';r.winner=username;const db=load();r.players.forEach(p2=>{const u=db.users[p2.username.toLowerCase()];if(!u)return;u.games++;if(p2.username===username){u.wins++;u.coins+=r.entry*r.players.length;u.xp+=100}else{u.losses++;u.xp+=10}});save(db)}else r.turn=(r.turn+1)%r.players.length;sync(r)});
s.on('disconnect',()=>{const r=rooms.get(s.data.roomId);if(!r)return;r.players=r.players.filter(p=>p.socketId!==s.id);if(!r.players.length&&r.id.startsWith('custom-'))rooms.delete(r.id);else sync(r)})});
server.listen(process.env.PORT||3001,()=>console.log('Guess It server running'));